import assert from "node:assert";
import * as fs from "node:fs/promises";
import {join} from "node:path";

import {describe, it} from "vitest";

import {generateBarrels} from "../bin/generate-barrel.js";

describe("barrels.integration.ts", () => {
  // eslint-disable-next-line vitest/expect-expect
  it("should generate barrels", async () => {
    const cwd = join(import.meta.dirname, "__mock__");
    // Test code here
    await generateBarrels({
      cwd,
      directory: ["./scenario-1"],
      exclude: ["**/__mock__", "**/__mocks__", "**/*.spec.ts"],
      delete: true
    });

    const result = await fs.readFile(join(cwd, "scenario-1", "index.ts"), "utf-8");

    assert.strictEqual(
      result,
      "/**\n" +
        " * @file Automatically generated by @tsed/barrels.\n" +
        " */\n" +
        'export * from "./file1.js";\n' +
        'export * from "./file2.js";\n' +
        'export * from "./sub-directory/file2.js";\n'
    );
  });
});
